# Generated by Django 3.2.12 on 2022-03-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AddField(
            model_name='task',
            name='msg',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
