# Generated by Django 3.2.12 on 2022-03-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_auto_20220325_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='img',
        ),
    ]
