# Generated by Django 3.2.12 on 2022-03-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0003_remove_task_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='msg',
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
