# Generated by Django 3.2.12 on 2022-03-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0004_auto_20220325_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AddField(
            model_name='task',
            name='msg',
            field=models.TextField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
