# Generated by Django 3.2.12 on 2022-03-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0005_auto_20220326_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='img',
            field=models.ImageField(default=5, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='msg',
            field=models.TextField(max_length=150),
        ),
    ]
